### ISSUE TITLE
shutil.which problem?!

### ISSUE THREAD

**Issue by argenisleon** [redsymbol/csv2parquet#2]
Hi,

I am getting this error:

  File "csv2parquet.py", line 330, in <module>
    drill = DrillInstallation()
  File "csv2parquet.py", line 203, in **init**
    assert reference_executable is not None
AssertionError

any help?

**Comment by gsemet** [comment]
you need to read the README and add the apache drill bin folder to the `PATH` environment variable.

**Comment by gnummeli** [comment]
That cannot be the only reason
I am getting the same error and I have verified back and forth that the drill bin folder is in the PATH
I'm using Linux Mint 18

**Comment by gnummeli** [comment]
Correction to my previous statement - the AssertionError is due to missing PATH indeed which I didn't notice is due to using sudo and that doesn't inherit the PATH variable from user.
But
what I get instead is an os level error:
Traceback (most recent call last):
  File "./csv2parquet", line 333, in <module>
    drill_script.run()
  File "./csv2parquet", line 265, in run
    os.rename(self.drill.location.full_path('parquet_tmp_output'), self.parquet_output)
OSError: [Errno 18] Invalid cross-device link: '/tmp/ihc4wg3x/parquet_tmp_output' -> 'aret.parquet'

which as far as I can ascertain has something to do with the privilege setting of the /tmp directory
Any suggestions?

**Comment by gnummeli** [comment]
Resolved
I replaced os.rename by shutil.move as recommended in another forum on stackoverflow and that solved the problem.
I.e. would recommend to do that change in the base program as well

**Comment by sanjeet12** [comment]
setting the environment variable for apache-drill solve the above problem
export PATH=$PATH:/home/Ubuntu/apache-drill-1.13.0/bin

But now it is showing 
FATAL: Drill script failed with error code 1.  To troubleshoot, run
with --debug and inspect files script, script_stderr and script_stdout.

How to solve this?

Thanks:)

**Comment by pmiola73** [comment]
> setting the environment variable for apache-drill solve the above problem
> export PATH=$PATH:/home/Ubuntu/apache-drill-1.13.0/bin
> 
> But now it is showing
> FATAL: Drill script failed with error code 1. To troubleshoot, run
> with --debug and inspect files script, script_stderr and script_stdout.
> 
> How to solve this?
> 
> Thanks:)

how did you solve it?
