### ISSUE TITLE
decode problem in csv2parquet

### ISSUE THREAD

**Issue by caijun** [redsymbol/csv2parquet#4]
Hi, I am using csv2parquet to convert csv into parquet, but I get following decode problem.

```
./csv2parquet all_cities.csv all_cities.parquet
Traceback (most recent call last):
  File "./csv2parquet", line 329, in <module>
    csv_source = CsvSource(args.csv_input, args.column_map, args.types)
  File "./csv2parquet", line 145, in __init__
    self.headers = self._init_headers()
  File "./csv2parquet", line 150, in _init_headers
    return next(csv_data)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 164: invalid continuation byte
```

**Comment by caijun** [comment]
After I used the iconv command to convert the file encoding from CP936 to UTF-8, I encountered another problem.

```
FATAL: Drill script failed with error code 2.  To troubleshoot, run
with --debug and inspect files script, script_stderr and script_stdout.
```

**Comment by titidutarn** [comment]
I got the same problem
solve: add "sudo" when entering your command line
