### ISSUE TITLE
Error related to com.google.common.base.Stopwatch

### ISSUE THREAD

**Issue by zbriesland** [redsymbol/csv2parquet#6]
Hello,

Thanks for this script.

I installed Apache Drill 1.10.0 on my (AWS) Linux server, and installed Python 3.6

When I run the script, after several seconds, the CLI returns without any error.

And I get an output file as specified in the params.

However, my output file is empty (the input file is 386 mb).

In the Drill logs, I get the error below.

This post (https://issues.apache.org/jira/browse/DRILL-4928) suggests that Netty 4.0.27 or later will cause this issue. 

I know very little about Drill or Netty.

Do you have any idea how I can work around this issue?

Thanks!

```
2017-04-06 19:06:02,948 [main] WARN  o.a.drill.exec.util.GuavaPatcher - Unable to patch Guava classes.
javassist.CannotCompileException: by java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/google/common/base/Stopwatch"
        at javassist.ClassPool.toClass(ClassPool.java:1085) ~[javassist-3.12.1.GA.jar:na]
        at javassist.ClassPool.toClass(ClassPool.java:1028) ~[javassist-3.12.1.GA.jar:na]
        at javassist.ClassPool.toClass(ClassPool.java:986) ~[javassist-3.12.1.GA.jar:na]
        at javassist.CtClass.toClass(CtClass.java:1079) ~[javassist-3.12.1.GA.jar:na]
```

**Comment by zbriesland** [comment]
Nevermind. I'm being dumb. That error doesn't appear to impair the output.
